DisableOwnerDamage: true
DisablePlayerDamagePlayers: true
DisablePlayerDamageEntities: true
DisableEntityDamagePlayers: true
DisableEntityDamageEntities: true
DisableLavaFlow: true
DisableWaterFlow: true
DisableExplosionDamage: false
DisableExplosions: true