DisableOwnerDamage: true
DisablePlayerDamagePlayers: true
DisablePlayerDamageEntities: true
DisableEntityDamagePlayers: true
DisableEntityDamageEntities: true
DisableLavaFlow: true
DisableWaterFlow: true
DisablePistons: true
DisableChestInteractions: true
DisableOtherInteractions: true
DisablePhysicalInteractions: true
DisableFarmInteractions: true
DisableExplosionDamage: false
DisableExplosions: true