DisableOwnerDamage: true
DisablePlayerDamagePlayers: true
DisablePlayerDamageEntities: true
DisableEntityDamagePlayers: true
DisableEntityDamageEntities: true
DisableExplosionDamage: false
DisableExplosions: true